server:  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e_commerce?characterEncoding=UTF-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
   
  jpa:    database: mysql
  
  cache:    type: redis
    thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    cache: true    mode: LEGACYHTML5
    servlet: 
      content-type: text/html; charset=utf-8
      
  mvc:
    static-path-pattern: /static/**
    
  resources:
    static-locations: classpath:/static/,file:/data/images/
    
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
                    # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
                    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # max-wait: -1
                    # 连接池中的最大空闲连接
        max-idle: 10
                   # 连接池中的最小空闲连接
        min-idle: 0
          # 连接超时时间（毫秒）
    timeout: 10000
    
  # RabbitMQ消息队列
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: 123456
    
mybatis:
  type-aliases-package: online.shixun.project.module.member.dto,
                        online.shixun.project.module.advertise.dto
                        online.shixun.project.module.commodity.dto,
                        online.shixun.project.module.order.dto,
                        online.shixun.project.module.spike.dto
  mapper-locations: classpath:mapper/*Mapper.xml
  
# MyBatis分页插件PageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
  

 